
Vagrant.configure("2") do |config|
  config.vm.box = "facilityenv-cenotos68.box"
  config.vm.network "private_network", ip: "192.168.2.10"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
   end
end
